services:
  local-database:
    container_name: thoughts-database
    image: "postgres:17-alpine"
    restart: always
    profiles:
      - dev
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: thoughts
    ports:
      - 5432:5432
    volumes:
      - ./.docker/database:/var/lib/postgresql/data # locally bound ".docker" folder
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql # init database with SQL files from local "database" folder

  database:
    container_name: thoughts-database
    image: "postgres:17-alpine"
    restart: always
    profiles:
      - prod
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: thoughts
    ports:
      - 3000:5432
    networks:
      - thoughts-network
    volumes:
      - database-data:/var/lib/postgresql/data # store data from postgresql in the volume
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql # init database with SQL files from local "database" folder

  assets-local:
    container_name: thoughts-assets
    image: "nginx:1.27.3-alpine"
    restart: always
    profiles:
      - dev
    ports:
      - 8000:80
    volumes:
      - ./.docker/assets:/usr/share/nginx/data/ # locally bound ".docker" folder
      - ./nginx/asset.conf:/etc/nginx/conf.d/default.conf

  assets:
    container_name: thoughts-assets
    image: "nginx:1.27.3-alpine"
    restart: always
    profiles:
      - prod
    ports:
      - 3001:80
    networks:
      - thoughts-network
      - cloudflared_tunnel
    volumes:
      - assets-data:/usr/share/nginx/data
      - ./nginx/asset.conf:/etc/nginx/conf.d/default.conf

  backend:
    container_name: thoughts-backend
    image: fredrikj31/thoughts-backend:latest
    restart: always
    profiles:
      - prod
    environment:
      WEBSITE_BASE_URL: ${WEBSITE_BASE_URL}
      JWT_PRIVATE_KEY: ${JWT_PRIVATE_KEY}
      PASSWORD_SALT: ${PASSWORD_SALT}
      DB_HOST: thoughts-database
      DB_PORT: 5432 # Must be set to "5432", because the backend and database shares network
      DB_NAME: thoughts
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    networks:
      - thoughts-network
      - cloudflared_tunnel
    ports:
      - 3002:3000

  frontend:
    container_name: thoughts-frontend
    image: fredrikj31/thoughts-frontend:latest
    restart: always
    profiles:
      - prod
    environment:
      MY_APP_API_BASE_URL: ${MY_APP_API_BASE_URL}
    networks:
      - cloudflared_tunnel
    ports:
      - 3003:80

networks:
  thoughts-network:
    driver: bridge
  cloudflared_tunnel:
    external: true

volumes:
  database-data:
    name: thoughts-database-data
    driver: local
  assets-data:
    name: thoughts-assets-data
    driver: local
