GET http://localhost:3000/users/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJkYmEyNmY3Ni05OTAwLTQ5YzAtYjkwMy1jYTI1ZTU5ODlmOTciLCJlbWFpbCI6ImpvaG5kb2VAbWFpbC5jb20iLCJ1c2VybmFtZSI6IkpvaG5Eb2UiLCJpYXQiOjE3MjM5ODEwOTcsImV4cCI6MTcyNDA2NzQ5N30.9DHhG8qdcoxMdlwPZ3AqadcSyn6LqvQ1iBbwXOdvEr0