POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "username": "johndoe",
  "email": "john@mail.com",
  "password": "Password123",
  "firstName": "John",
  "lastName": "Doe",
  "birthDate": "1900-01-01",
  "gender": "MALE"
}